[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "lucidity"
version = "0.1.0"
description = "Turn-based simulation game"
readme = "PRD.md"
requires-python = ">=3.8"

[project.scripts]
lucidity = "lucidity.cli:main"
